import { useMemo, useState } from 'react'
import {
  AlertTriangle,
  CheckCircle2,
  Clock3,
  ShieldAlert,
} from 'lucide-react'

import AlertFilters from '../components/alerts/AlertFilter'
import AlertList from '../components/alerts/AlertList'

const alerts = [
  {
    id: 1,
    title: 'Unknown Vessel Detected',
    description:
      'AI detection identified a vessel operating without a matching AIS identity.',
    severity: 'High',
    status: 'Unreviewed',
    location: 'Offshore Zone A',
    time: '2 min ago',
    confidence: 94,
  },
  {
    id: 2,
    title: 'AIS Signal Lost',
    description:
      'A previously tracked vessel stopped transmitting AIS information.',
    severity: 'Medium',
    status: 'Under Review',
    location: 'Surveillance Zone B',
    time: '8 min ago',
    confidence: 87,
  },
  {
    id: 3,
    title: 'Route Deviation Detected',
    description:
      'Vessel movement differs significantly from its expected route.',
    severity: 'Medium',
    status: 'Unreviewed',
    location: 'Offshore Zone C',
    time: '15 min ago',
    confidence: 81,
  },
  {
    id: 4,
    title: 'Unusual Vessel Activity',
    description:
      'Movement pattern indicates extended activity within a monitored zone.',
    severity: 'Low',
    status: 'False Positive',
    location: 'Surveillance Zone A',
    time: '24 min ago',
    confidence: 72,
  },
]

function Alerts() {
  const [search, setSearch] = useState('')
  const [severity, setSeverity] = useState('all')
  const [status, setStatus] = useState('all')

  const filteredAlerts = useMemo(() => {
    return alerts.filter((alert) => {
      const matchesSearch =
        alert.title.toLowerCase().includes(search.toLowerCase()) ||
        alert.description.toLowerCase().includes(search.toLowerCase()) ||
        alert.location.toLowerCase().includes(search.toLowerCase())

      const matchesSeverity =
        severity === 'all' ||
        alert.severity.toLowerCase() === severity

      const matchesStatus =
        status === 'all' ||
        alert.status.toLowerCase().replaceAll(' ', '-') === status

      return matchesSearch && matchesSeverity && matchesStatus
    })
  }, [search, severity, status])

  const highCount = alerts.filter(
    (alert) => alert.severity === 'High'
  ).length

  const unreviewedCount = alerts.filter(
    (alert) => alert.status === 'Unreviewed'
  ).length

  const confirmedCount = alerts.filter(
    (alert) => alert.status === 'Confirmed'
  ).length

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <p className="text-sm text-emerald-400">
          Incident Management
        </p>

        <div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div className="min-w-0">
            <h1 className="text-2xl font-semibold text-white">
              Alerts
            </h1>

            <p className="mt-1 max-w-2xl text-sm leading-5 text-slate-500">
              Review, investigate and manage maritime surveillance alerts
              generated by the detection and fusion systems.
            </p>
          </div>

          <div className="flex shrink-0 items-center gap-2 text-xs text-slate-500">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
            Monitoring active
          </div>
        </div>
      </div>

      {/* Alert Summary */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <SummaryCard
          label="Total Alerts"
          value={alerts.length}
          icon={AlertTriangle}
          description="Current alert records"
        />

        <SummaryCard
          label="High Severity"
          value={highCount}
          icon={ShieldAlert}
          description="Require priority review"
          valueClass="text-red-400"
        />

        <SummaryCard
          label="Unreviewed"
          value={unreviewedCount}
          icon={Clock3}
          description="Awaiting analyst review"
          valueClass="text-amber-400"
        />

        <SummaryCard
          label="Confirmed"
          value={confirmedCount}
          icon={CheckCircle2}
          description="Analyst verified incidents"
          valueClass="text-emerald-400"
        />
      </div>

      {/* Filters */}
      <AlertFilters
        search={search}
        setSearch={setSearch}
        severity={severity}
        setSeverity={setSeverity}
        status={status}
        setStatus={setStatus}
      />

      {/* Result Count */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-sm font-semibold text-white">
            Active Alert Records
          </h2>

          <p className="mt-1 text-xs text-slate-500">
            {filteredAlerts.length} of {alerts.length} alerts displayed
          </p>
        </div>

        <span className="w-fit rounded-full border border-slate-800 bg-slate-900 px-3 py-1 text-[10px] uppercase tracking-wider text-slate-500">
          Live Queue
        </span>
      </div>

      {/* Alert List */}
      {filteredAlerts.length > 0 ? (
        <AlertList alerts={filteredAlerts} />
      ) : (
        <EmptyState />
      )}
    </div>
  )
}

function SummaryCard({
  label,
  value,
  icon: Icon,
  description,
  valueClass = 'text-white',
}) {
  return (
    <div className="group rounded-xl border border-slate-800 bg-slate-900 p-4 transition duration-200 hover:border-slate-700">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-[10px] font-medium uppercase tracking-wider text-slate-500">
            {label}
          </p>

          <p
            className={`mt-2 text-2xl font-semibold tracking-tight ${valueClass}`}
          >
            {value}
          </p>
        </div>

        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-800">
          <Icon className="h-4 w-4 text-slate-400 transition group-hover:text-slate-300" />
        </div>
      </div>

      <p className="mt-3 text-xs text-slate-600">
        {description}
      </p>
    </div>
  )
}

function EmptyState() {
  return (
    <div className="flex min-h-56 flex-col items-center justify-center rounded-xl border border-dashed border-slate-800 bg-slate-900/50 px-6 text-center">
      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-800">
        <AlertTriangle className="h-4 w-4 text-slate-500" />
      </div>

      <h3 className="mt-4 text-sm font-medium text-white">
        No alerts found
      </h3>

      <p className="mt-1 max-w-sm text-xs leading-5 text-slate-500">
        No alert records match the current search and filter criteria.
      </p>
    </div>
  )
}

export default Alerts